### ISSUE TITLE
Add additional client info to API endpoint request

### ISSUE THREAD

**Issue by billdami** [kredde/ember-error-tracker#12]
Hi, thanks for your work on this addon!

I was wondering if you'd be able to add some additional values to the API endpoint consumer's ajax request, specifically:

* `currentUrl`
* `resolution` (e.g. `window.screen.width/height`)
* `viewPort` (e.g. `window.innerWidth/innerHeight`)

Also, I have not tested this yet, but is this addon compatible with FastBoot? Or has guards to prevent running non-node.js compatible code (e.g. accessing `window`, etc) while in FastBoot?

Thanks!

**Comment by kredde** [comment]
Hi!
Yes, sure I will add these properties as they sound reasonable to me. 
I have not tested it with FastBoot, however, I've put guards to check if  `window` is defined whenever it is accessed.

**Comment by billdami** [comment]
@kredde great, thank you!
