### ISSUE TITLE
FastBoot compatibility fixes 

### ISSUE THREAD

**Issue by billdami** [kredde/ember-error-tracker#14]
Thanks again for adding those new properties @kredde they look great!

I did, however, notice some small issues while running the addon in FastBoot still. Specifically, if an error is thrown when the app runs in fastboot, I'm getting:

```
(node:81599) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'width' of undefined
```
and
```
(node:81599) UnhandledPromiseRejectionWarning: ReferenceError: navigator is not defined
```

It looks like `window` itself still exists in FastBoot, so the guards have to be a bit more specific I think. I was able to resolve these with some local modifications to the addon's `consumers/consumer.js` file:

```js
consumeError(error) {
    //...

    if (window && window.screen) {
        //...
    }

    if (window && window.location) {
        //...
    }

    const payload = {
        error,
        userAgent: window && window.navigator ? window.navigator.userAgent : undefined,
        screen,
        location,
        events: this.eventStack.array
    };

    //...
}
```
This appears to be the recommended pattern for these issues:  
https://ember-fastboot.com/docs/addon-author-guide#how-to-fix-it

**Comment by kredde** [comment]
@billdami Ok I added the proposed checks, should be working now.
